services:
  empyrion-dedicated:
    build:
      context: .
      tags:
        - tupinumboor/empyrion-dedicated:latest
        - tupinumboor/empyrion-dedicated:1.0

    image: tupinumboor/empyrion-dedicated:latest
    restart: unless-stopped

    environment:
      - VALIDATE_GAME_FILES=false

    ports:
      - "30000:30000/udp"

    volumes:
      - ./steam:/home/steam/Steam
      - ./config:/config:ro
